Workshop docker image for the workflow-array-ephys
datajoint/workflow-array-ephys pull request #22
Opened 2021-09-01 17:09 UTC by Yambottle

This is different from the present `Dockerfile`, so named it as `Dockerfile.workshop`

2021-09-01 17:11 UTC, Yambottle commented
@ttngu207

2021-12-22 20:47 UTC, kabilar commented on Dockerfile.workshop
> +## Install datajoin dependencies
```suggestion
## Install datajoint dependencies
```

2021-12-22 20:48 UTC, kabilar commented on Dockerfile.workshop
> +# RUN chmod 775 /usr/local/bin/before-notebook.d/file_injector.sh
Generally speaking, please remove commented code.

2021-12-22 20:52 UTC, kabilar requested changes
Thanks @Yambottle.  A few thoughts listed below.

- Should we move the file changes in `.datajoint_config.json` and `Dockerfile.workshop` to somewhere in the `vathes` GitHub organization since this is specific to our JupyterHub configuration?  The files within `workflow-array-ephys` are meant for more general community use without our hosted resources.

- Please remove `tests/test_export.py` as the NWB export function in `element-array-ephys` is not quite ready for release.

2021-12-22 23:39 UTC, Yambottle commented
> Thanks @Yambottle. A few thoughts listed below.
> 
> * Should we move the file changes in `.datajoint_config.json` and `Dockerfile.workshop` to somewhere in the `vathes` GitHub organization since this is specific to our JupyterHub configuration?  The files within `workflow-array-ephys` are meant for more general community use without our hosted resources.
> * Please remove `tests/test_export.py` as the NWB export function in `element-array-ephys` is not quite ready for release.

This was a long-time-ago PR that I wasn't sure where to put this workshop dockerfile, I'll move it to vathes/dj-ops-tf since that repo is more devops general

2021-12-22 23:42 UTC, Yambottle commented
@kabilar I'd recommend to abandon this PR, since everything is so outdated

2021-12-22 23:53 UTC, kabilar commented
Thanks @Yambottle.  That sounds like a good plan.  I will close this pull request as many of the remaining changes are in #18.

2021-12-22 23:53 UTC, closed without merging