Codebook env docker | cicd generated from dj-cookiecutter
datajoint/workflow-array-ephys pull request #56
Opened 2022-03-25 19:27 UTC by Yambottle

2022-03-30 15:35 UTC, guzman-raphael requested changes
@yambottle Looks good. :+1: 

Added similar point from other review.

2022-03-30 15:35 UTC, guzman-raphael commented on docker/codebook.Dockerfile
> +ARG DEPLOY_KEY
Similar to point in other [review](https://github.com/datajoint/workflow-calcium-imaging/pull/63#pullrequestreview-926324490).

2022-05-01 01:17 UTC, kabilar commented
Thank you for taking the time to put this together, @yambottle!  I will defer to @guzman-raphael to review this work.

I have only one question.  One goal for this repository is to be didactic by allowing users to clone and run the pipeline themselves.  Would it make sense to move these DataJoint company-specific settings (that a user would not need) to another repository?  Thanks.

2022-08-25 20:18 UTC, Ernaldis approved these changes

2022-08-25 20:24 UTC, merged