Revise pytests/docker, markdown lint, pre-commit, spell check cleanup, NWB test update
datajoint/workflow-array-ephys pull request #89
Opened 2023-01-17 23:07 UTC by CBroz1

I recommend reviewers select sets of commits to review, as some are formatting/spelling only, rather than substantive.

### Submission checklist

- [ ] Reviewed all `Files changed` prior to selecting `Create Pull Request`.
- [ ] Ran and passed all pytests, and ran the pipeline for features not covered by tests.
- [ ] Ran pre-commit checks, including black, flake8, etc.
- [ ] Updated the changelog and if making a new release, updated the version.py.
- [ ] Updated documentation, including concepts.md, tutorials.md, and relevant docstrings.
- [ ] After merge, I will push a new tag to upstream (test* prefix if no new release).

### Submission details

In this pull request, I make the following changes:
- Concept: Why?
   - File: specifics
   - File: specifics

2023-01-18 18:32 UTC, JaerongA requested changes

2023-01-18 18:32 UTC, JaerongA commented on setup.py
> +    version=__version__,  # noqa: F821
```suggestion
    python_requires=">=3.7",
    version=__version__,  # noqa: F821
```

2023-01-18 18:48 UTC, CBroz1 commented on StandardConfig.json
> +}
Not sure. It looks like @ttngu207 added it with [this commit](https://github.com/datajoint/workflow-array-ephys/commits/main/StandardConfig.json)

2023-01-18 22:09 UTC, JaerongA commented on tests/conftest.py
> +@pytest.fixture(autouse=True, scope="session")
```suggestion
@pytest.fixture(scope="session")
```

Can we remove `autouse=True` for this one? Sometime I'd like to run a quick test only on pipeline generation without having to download all the test data. Looks like `ingest_data` calls this fixture.

2023-01-20 17:05 UTC, JaerongA approved these changes

2023-01-20 21:01 UTC, merged